name: brickdb
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=brickDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123
    ports:
      - 3307:3306
    volumes:
      - ./target/:/app/
  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"